### ISSUE TITLE
Missing command error when getting cookie 

### ISSUE THREAD

**Issue by bdsvalencia** [kristianhristov/cordova-cookie-master#17]
cookieMaster.getCookieValue('http://phmavclmdb1.infor.com:21007/REST', 'IRCVMLKHOJUWILKWGI5DUOR2', function (data) {
		      console.log(data.cookieValue);
		    }, function (error) {
		      if (error) {
		        console.log('error: ' + error);
		      }
		    });
also tried 
cookieMaster.getCookieValue('http://phmavclmdb1.infor.com:21007', 'IRCVMLKHOJUWILKWGI5DUOR2', function (data) {
		      console.log(data.cookieValue);
		    }, function (error) {
		      if (error) {
		        console.log('error: ' + error);
		      }
		    });

But I got Missing command error. I hope you could help me. Im using Windows 10.

**Comment by kristianhristov** [comment]
This plug in was created for iOS and Android platforms. It does NOT support windows platforms. Maybe that is the why you are getting the issue.
