### ISSUE TITLE
Cookies are not getting set when using WKWebview Kit iOS ionic

### ISSUE THREAD

**Issue by shrivallabhDeshmukh** [kristianhristov/cordova-cookie-master#21]
Cookies are not getting set after implementation WKWebview kit in IOS

Please help!

Ionic info
Ionic:

   ionic (Ionic CLI)  : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.1, (and 23 other plugins)

System:

   NodeJS : v10.15.3 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
   Xcode  : Xcode 10.2 Build version 10E125

**Comment by kristianhristov** [comment]
Please note that this project is no longer maintained and therefore is likely not to work with modern versions of iOS and Android. Please look for alternatives.
